language:
  php

php:
  - '7.1'
  - '7.2'
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml --testdox
  - vendor/bin/infection --min-msi=100 --min-covered-msi=100
  - vendor/bin/phpstan analyse src tests --level=7 --no-progress

after_success:
  - travis_retry php vendor/bin/php-coveralls
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
